version: '3.3'
services:
  minio:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/minio:dev
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    ports:
      - 9000:9000
      - 9001:9001
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3