version: '3.3'
services:
  superset:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/superset:dev
    container_name: superset
    user: root
    network_mode: "bridge"
    restart: always
    ports:
      - 8088:8088
    # volumes:
    #   - /bigdata/superset:/var/superset

# docker-compose stop && docker-compose rm -f