version: '3.3'
services:
  superset:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/superset:dev
    container_name: superset
    user: root
    network_mode: "bridge"
    restart: always
    ports:
      - 9088:8088
      - 9088:8888
    mem_limit: 8g
    extra_hosts:
      - "ubuntu.livenowhy.com:192.168.65.101"
    volumes:
      - /home/lzp/Desktop/makefile/23_superset/02_dev/superset_config.py:/usr/local/lib/python3.10/site-packages/superset/superset_config.py
      - /home/lzp/Desktop/makefile/23_superset/02_dev/gunicore_superset.sh:/app/gunicore_superset.sh
      
# docker-compose stop && docker-compose rm -f
