version: '3.3'
services:
  mysql8:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/mysql:5.6.base
    container_name: mysql8
    network_mode: "bridge"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 8082:3306
    volumes:
      - /bigdata/mysql8:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Qp9tb869zXu4kh7Gm9R"
      
  adminer:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/adminer:4.8.1-standalone
    container_name: adminer
    network_mode: "bridge"
    restart: always
    ports:
      - 8081:8080

# docker-compose stop && docker-compose rm -f