FROM registry.cn-beijing.aliyuncs.com/livenowhy/python:3.10.14-bookworm-ai

LABEL description="django debug 运行镜像; 基于 3.10.14-bookworm-ai"


RUN pip install --no-cache-dir pyjwt
RUN pip install --no-cache-dir sseclient

# /07_python/06_3.10.14-bookworm-debug/
