FROM docker.io/certbot/certbot:latest

# registry.cn-beijing.aliyuncs.com/livenowhy/certbot:latest
# docker run -it --rm --name certbot -v "/etc/letsencrypt:/etc/letsencrypt" -v "/var/lib/letsencrypt:/var/lib/letsencrypt" certbot/certbot certonly
# docker run -it --rm --name certbot registry.cn-beijing.aliyuncs.com/livenowhy/certbot:latest certonly