FROM minio/minio:RELEASE.2020-12-03T00-03-10Z
LABEL description="minio:RELEASE.2020-12-03T00-03-10Z"


# export MINIO_ROOT_USER=admin
# export MINIO_ROOT_PASSWORD=admin123
# chmod +x minio
# ./minio server /data

# docker tag registry.cn-beijing.aliyuncs.com/livenowhy/minio:apache registry.cn-beijing.aliyuncs.com/oopen/minio:apache

# registry.cn-beijing.aliyuncs.com/livenowhy/minio:apache
# docker save -o minio_apache.tar registry.cn-beijing.aliyuncs.com/livenowhy/minio:apache
# docker save -o alpine_3.16.tar registry.cn-beijing.aliyuncs.com/livenowhy/alpine:3.16