FROM registry.cn-beijing.aliyuncs.com/livenowhy/python:3.10.14-bookworm-dev

LABEL description="ollama 运行基础镜像; 基于 python:3.10.14-bookworm-dev"

# 1. ollama 
RUN curl -fsSL https://ollama.com/install.sh | sh

# registry.cn-beijing.aliyuncs.com/livenowhy/ollama:base