FROM registry.cn-beijing.aliyuncs.com/livenowhy/python:3.10.14-bookworm-pycaret

LABEL description="django pycaret 运行镜像; 基于 3.10.14-bookworm-crewai"

# 1. ollama 
RUN curl -fsSL https://ollama.com/install.sh | sh