version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: registry.cn-beijing.aliyuncs.com/oopen/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /Users/zpliu/Desktop/share/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: registry.cn-beijing.aliyuncs.com/livenowhy/minio:apache
    # image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - /Users/zpliu/Desktop/share/volumes/minio:/minio_data

  # minio:
  #   container_name: milvus-minio
  #   image: registry.cn-beijing.aliyuncs.com/livenowhy/minio:RELEASE.2020-12-03
  #   environment:
  #     MINIO_ACCESS_KEY: 'minioadmin'
  #     MINIO_SECRET_KEY: 'minioadmin'
  #   volumes:
  #     - /Users/zpliu/Desktop/share/volumes/minio:/minio_data
  #   command: minio server /minio_data
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
      
  standalone:
    container_name: milvus-standalone
    image: registry.cn-beijing.aliyuncs.com/oopen/milvus:v2.5.9
    command: ["milvus", "run", "standalone"]
    # security_opt:
    # - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - /Users/zpliu/Desktop/share/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

  attu:
    container_name: milvus-attu
    # image: registry.cn-beijing.aliyuncs.com/oopen/attu:v2.3.1
    image: registry.cn-beijing.aliyuncs.com/oopen/attu:v2.5.6
    environment:
      MILVUS_URL: standalone:19530
    ports:
      - "8080:3000"
    depends_on:
      - "etcd"
      - "minio"
      - "standalone"

networks:
  default:
    name: milvus

# https://www.miaokee.com/2555968.html