FROM registry.cn-beijing.aliyuncs.com/livenowhy/django:jupyterlab

# 1. crewai 配置
RUN pip install --no-cache-dir crewai==0.120.1
RUN pip install --no-cache-dir crewai-tools==0.45.0
RUN pip install --no-cache-dir duckduckgo_search==8.0.2
RUN pip install --no-cache-dir langchain==0.3.25
RUN pip install --no-cache-dir langchain-community==0.3.24
RUN pip install --no-cache-dir ollama==0.4.8