version: '3.3'
services:
  superset:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/superset:dev
    container_name: superset
    user: root
    network_mode: "bridge"
    privileged: true
    restart: always
    ports:
      - 9088:8088
      - 8888:8888
      - 8088:8080
      - 8082:8082
      - 8083:8083
      - 8084:8084
      - 8085:8085
    mem_limit: 8g
    extra_hosts:
      - "ubuntu.livenowhy.com:192.168.43.167"
    volumes:
      - /share/superset:/usr/local/lib/python3.10/site-packages/superset
      - ./run-server.sh:/app/run-server.sh
      - ./supervisord/superset.ini:/etc/supervisord.d/superset.ini
      - ./supervisord/jupyter.ini:/etc/supervisord.d/jupyter.ini
      - ./supervisord/codeserver.ini:/etc/supervisord.d/codeserver.ini
      - ./supervisord/mlflow.ini:/etc/supervisord.d/mlflow.ini

# sudo docker-compose stop && sudo docker-compose rm -f
