version: '3.3'
services:
  superset:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/superset:dev
    container_name: superset
    user: root
    network_mode: "bridge"
    restart: always
    ports:
      - 9088:8088
      - 8888:8888
    mem_limit: 8g
    extra_hosts:
      - "ubuntu.livenowhy.com:192.168.43.167"
    volumes:
      - /share/makefile/23_superset/04_dev/superset_config.py:/usr/local/lib/python3.10/site-packages/superset/superset_config.py
      - /share/makefile/23_superset/04_dev/:/app/04_dev/

# sudo docker-compose stop && sudo docker-compose rm -f