version: '3.3'
services:
  superset:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/superset:dev
    container_name: superset
    user: root
    network_mode: "bridge"
    privileged: true
    restart: always
    ports:
      - 9088:8088  # superset
      - 8888:8888  # jupyter
      - 8088:8080  # codeserver
      - 8082:8082  # mlflow
      - 8083:8083
      - 8084:8084
      - 8085:8085
    extra_hosts: 
      - "raw.githubusercontent.com:185.199.108.133"
    mem_limit: 8g
    volumes:
      - /share/superset:/usr/local/lib/python3.10/site-packages/superset
      - ./run-server.sh:/app/run-server.sh
      - ./supervisord/superset.ini:/etc/supervisord.d/superset.ini
      - ./supervisord/jupyter.ini:/etc/supervisord.d/jupyter.ini
      - ./supervisord/codeserver.ini:/etc/supervisord.d/codeserver.ini
      - ./supervisord/mlflow.ini:/etc/supervisord.d/mlflow.ini
      - /share/jupyter:/app/jupyter

# sudo docker-compose stop && sudo docker-compose rm -f
