version: '3.3'
services:
  crewai:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/python:3.10.14-bookworm-crewai
    container_name: crewai
    user: root
    network_mode: "bridge"
    privileged: true
    restart: always
    ports:
      - 8092:11434   # crewai
    environment:
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
      OLLAMA_HOST: 0.0.0.0:11434
    extra_hosts: 
      - "raw.githubusercontent.com:185.199.108.133"
    mem_limit: 8g
    volumes:
      - ../supervisord/crewai.ini:/etc/supervisord.d/crewai.ini
      - /bigdata/mlflow:/share/mlflow
      - /share/mlops:/share/mlops
      - /bigdata/ollama:/root/.ollama/
      - ../run-server.sh:/share/run-server.sh