version: '3.3'
services:
  jenkins:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/jenkins:blueocean1.25.7
    container_name: jenkins
    user: root
    network_mode: "bridge"
    restart: always
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - /bigdata/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

# docker-compose stop && docker-compose rm -f
# TEST: user: admin, passwd: admin@admin