version: '3.3'
services:
  django:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/ubuntu:python
    container_name: django
    network_mode: "bridge"
    restart: always
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
      - 8005:8005
      - 8006:8006
      - 8007:8007
      - 8008:8008
    volumes:
      - /share/notebooks:/share/notebooks
      - /share:/share