version: '3.3'
services:
  django:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/ubuntu:django
    container_name: django
    network_mode: "bridge"
    restart: always
    extra_hosts:
      - "localnas.livenowhy.com:192.168.2.101"
    ports:
      - 8011:8011
      - 8012:8012
      - 8013:8013
      - 8014:8014
      - 8015:8015
      - 8016:8016
      - 8017:8017
      - 8018:8018
      - 8019:8019
    volumes:
      - /share/notebooks:/share/notebooks
      - /share:/share
      