version: '3.3'
services:
  django:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/centos:ccb
    container_name: ccb-develop
    network_mode: "bridge"
    restart: always
    command: sh /share/makefile/docker_compose/script/daemon.sh
    ports:
      - 8002:8002
    volumes:
      - /share/makefile/docker_compose/script:/share/makefile/docker_compose/script
      