version: '3.3'
services:
  jenkins:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/jenkins:2.303.2
    container_name: jenkins
    network_mode: "bridge"
    restart: always
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - /bigdata/jenkins:/var/jenkins

# docker-compose stop && docker-compose rm -f
