FROM registry.cn-beijing.aliyuncs.com/livenowhy/minio:latest
LABEL description="minio dev"

RUN yes | cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# registry.cn-beijing.aliyuncs.com/livenowhy/minio:dev