FROM registry.cn-beijing.aliyuncs.com/livenowhy/minio:latest
LABEL description="minio dev"

RUN echo 'Etc/UTC' >/etc/timezone
# registry.cn-beijing.aliyuncs.com/livenowhy/minio:dev
# docker save -o minio_devgit.tar registry.cn-beijing.aliyuncs.com/livenowhy/minio:dev 

# environment:
    # - TZ=America/New_York