version: '3.3'
services:
  mysql:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/mysql:5.6.base
    container_name: mysql
    network_mode: "bridge"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /bigdata/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Qp9tb869zXu4kh7Gm9R"
      MYSQL_DATABASE: cmdb

  # mysql8:
  #   image: registry.cn-beijing.aliyuncs.com/livenowhy/mysql:8.0.base
  #   command: --default-authentication-plugin=mysql_native_password
  #   container_name: mysql8
  #   network_mode: "bridge"
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - /bigdata/mysql8:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "Qp9tb869zXu4kh7Gm9R"
  
  # adminer:
  #   image: registry.cn-beijing.aliyuncs.com/livenowhy/adminer:4.8.1-standalone
  #   restart: always
  #   network_mode: "bridge"
  #   ports:
  #     - 8002:8080
      
  redis:
    image: registry.cn-beijing.aliyuncs.com/livenowhy/redis:6.0.base
    container_name: db_redis
    network_mode: "bridge"
    restart: always
    ports:
      - 6379:6379

  # rabbitmq:
  #   hostname: rabbitmq
  #   image: registry.cn-beijing.aliyuncs.com/livenowhy/rabbitmq:3.8-management
  #   container_name: rabbitmq
  #   network_mode: "bridge"
  #   restart: always
  #   ports:
  #     - 15672:15672
  #     - 4369:4369
  #     - 5672:5672
  #     - 25672:25672
  #     - 5671:5671
  #   volumes:
  #     - /bigdata/rabbitmq:/var/lib/rabbitmq

  # mongo:
  #   image: registry.cn-beijing.aliyuncs.com/livenowhy/mongo:6.0.1
  #   container_name: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - /bigdata/mongo:/data/db

  # mongo-express:
  #   image: registry.cn-beijing.aliyuncs.com/livenowhy/mongo-express:1.0.0-alpha.4
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongo
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     # mongo 的链接地址

# docker-compose stop && docker-compose rm -f